const CC_SINGLE_QUOTE = 39;
const CC_DOUBLE_QUOTE = 34;
const CC_DASH = 45;
const CC_SLASH = 47;
const CC_STAR = 42;
const CC_NEWLINE = 10;
const CC_QUESTION = 63;
const CC_SEMICOLON = 59;
const CC_SPACE = 32;

const STATE_NORMAL = 0;
const STATE_SINGLE_QUOTE = 1;
const STATE_DOUBLE_QUOTE = 2;
const STATE_LINE_COMMENT = 3;
const STATE_BLOCK_COMMENT = 4;

export {
	CC_SINGLE_QUOTE,
	CC_DOUBLE_QUOTE,
	CC_DASH,
	CC_SLASH,
	CC_STAR,
	CC_NEWLINE,
	CC_QUESTION,
	CC_SEMICOLON,
	CC_SPACE,
	STATE_NORMAL,
	STATE_SINGLE_QUOTE,
	STATE_DOUBLE_QUOTE,
	STATE_LINE_COMMENT,
	STATE_BLOCK_COMMENT,
};
